# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 53f1847c9b7da929bf150c4c5e1cf3df04fe3393810b855d82b2e724362a7a8d22ed9fd6fe749fbef5af50fe14f2dc1d44ba8de528f2787fd6f9581c1b459d04

test:
  secret_key_base: b9e6592ab1b5272217a367255e533d39961bfc282980c05be8a9c6f0fa3f58a225d3781ea8cf8a09eaccfed6ca3392a681b97ace46076cb91ad4da1125ab624c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
